# Testing using REST client with VS Code

@baseUrl = http://localhost:6090/api


###
post {{baseUrl}}/user/create

Content-Type: application/json
{
  "fullname": "Ndevu User",
  "username": "Ndevu",
  "email": "ndevulion@gmail.com",
  "password": "@K1234passkey",
  "phoneNumber": 0735044398,
  "role": "admin"
}
###
get {{baseUrl}}/author/661cf15c82b208b5abf3da07
###
get {{baseUrl}}/blog/all
###
get {{baseUrl}}/api/blogCategory/all

###
get {{baseUrl}}/api/blogCatecory/661cd4e528e17db0050a873e
# post {{{baseUrl}}}/api/blog/
###
patch  {{baseUrl}}/api/blog/update

Content-Type: application/json
{
  "title": "My first blog yugijokotyuiop",
  "content": "This is my first blog post so, Button and add a name to your test, 123",
  "description": "button and add afcgvhbjnkml;fgvbhjnm name to your test. You will be redirected to the page from where you can create the tests. Select an endpoint that",
  "category": "661bc8ff537e31bb91cacc7d",
  "tags": ["Science", "Technology", "Social Life"]
}

