# Testing using REST client with VS Code

@baseUrl = http://localhost:6090/api


###
put {{baseUrl}}/user/create

Content-Type: application/json
{
  "fullname": "Ndevu User",
  "username": "Ndevu",
  "email": "ndevulion@gmail.com",
  "password": "@K1234passkey",
  "phoneNumber": 0735044398,
  "role": "admin"
}

###
get {{baseUrl}}/user/login
Content-Type: application/json
Authorization: Bearer {{'a7fd8b3f9c2e4579fbf43dc56e1e0e244d34d9c4b11d8b826c8398f9c6dc3ebf'}}

{
  "username": "Ndevu",
  "password": "K1234pas131nonomo"
}

###
get {{baseUrl}}/author/661cf15c82b208b5abf3da07
###
get {{baseUrl}}/blog/all
###
get {{baseUrl}}/api/blogCategory/all

###
get {{baseUrl}}/blogCatecory/661cd4e528e17db0050a873e
# post {{{baseUrl}}}/blog/
###
put  {{baseUrl}}/blog/update

Content-Type: application/json
{
  "title": "My first blog yugijokotyuiop",
  "content": "This is my first blog post so, Button and add a name to your test, 123",
  "description": "button and add afcgvhbjnkml;fgvbhjnm name to your test. You will be redirected to the page from where you can create the tests. Select an endpoint that",
  "category": "661bc8ff537e31bb91cacc7d",
  "tags": ["Science", "Technology", "Social Life"]
}

###
post {{baseUrl}}/blog/create

Content-Type: application/json
{
  "title": "My first blog yugijokotyuiop",
  "content": "This is my first blog post so, Button and add a name to your test, 123",
  "description": "button and add afcgvhbjnkml;fgvbhjnm name to your test. You will be redirected to the page from where you can create the tests. Select an endpoint that",
  "category": "661bc8ff537e31bb91cacc7d",
  "tags": ["Science", "Technology", "Social Life"]
}